separator=true
separator_block_width=15

[volume]
command=~/.config/i3blocks/conf.d/scripts/volume.sh
interval=1
markup=none

# Add these to ensure the click area is "solid"
min_width=100%
align=center
# Alternatively, use signal-based updates to save resources
# interval=once
#signal=10
# This line is crucial for some versions of i3blocks
#min_width=   100%