# Global properties
separator=true
separator_block_width=15

[cpu_usage]
label=CPU:
command=/usr/share/i3blocks/cpu_usage
interval=10

[memory]
label=MEM:
command=/usr/share/i3blocks/memory
interval=30

[memory]
label=SWAP:
instance=swap
separator=false
interval=30

[disk]
label=HOME 
instance=$HOME
command=/usr/share/i3blocks/disk
interval=30

[iface]
command=/usr/share/i3blocks/iface
color=#00FF00
interval=10
separator=false

[network]
label=NET: 
command=/usr/share/i3blocks/bandwidth
interval=5

[aqi]
label=AQI
# this token gets set in ~/.profile
command=curl -s https://api.waqi.info/feed/here/?token=${WAQI_TOKEN} | jq '.data.aqi'
interval=3600
color=#91E78B

[weather]
command=curl -s "wttr.in?format=%c+%t"
interval=3600
color=#A4C2F4
min_width=   100%

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=5

